# Generated by Django 5.1 on 2024-09-26 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Examenes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preguntas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Texto_Pregunta', models.TextField(verbose_name='Detalle')),
                ('Nivel_Dificultad', models.CharField(choices=[('B', 'Basico'), ('M', 'Intermedio'), ('A', 'Avanzado')], max_length=1, verbose_name='Niveles')),
                ('ID_Examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Examenes.examenes')),
            ],
        ),
        migrations.CreateModel(
            name='Opciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo_Opcion', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1, verbose_name='id Opciones')),
                ('Texto_Opción', models.CharField(max_length=200, verbose_name='opcion')),
                ('Es_Correcta', models.BooleanField(default=False)),
                ('ID_Pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Preguntas.preguntas')),
            ],
        ),
    ]
