# Generated by Django 5.1 on 2024-09-27 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Preguntas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opciones',
            options={'verbose_name': 'Opciones del Examen', 'verbose_name_plural': 'Opciones'},
        ),
        migrations.AlterModelOptions(
            name='preguntas',
            options={'verbose_name': 'Preguntas del Examen', 'verbose_name_plural': 'Preguntas'},
        ),
    ]
