# Generated by Django 5.1 on 2024-10-20 15:10

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Preguntas', '0002_alter_opciones_options_alter_preguntas_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntas',
            name='Texto_Pregunta',
            field=django_quill.fields.QuillField(),
        ),
    ]
