# Generated by Django 5.1 on 2024-10-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Preguntas', '0003_alter_preguntas_texto_pregunta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntas',
            name='Texto_Pregunta',
            field=models.TextField(verbose_name='Descripción'),
        ),
    ]
