# Generated by Django 5.1 on 2024-09-26 02:10

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Categoría', models.CharField(max_length=6, unique=True, verbose_name='Area tematica')),
                ('Nombre_Categoría', models.CharField(max_length=30, verbose_name='nombre Area')),
            ],
        ),
        migrations.CreateModel(
            name='Examenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Examen', models.CharField(max_length=30, unique=True, verbose_name='Area tematica')),
                ('Descripción', models.TextField(verbose_name='Detalle')),
                ('Fecha_Creación', models.DateField(default=datetime.date.today, verbose_name='Fecha de creacion')),
                ('Duración_Límite', models.IntegerField(default=5, verbose_name='Duracion en minutos')),
                ('Categoría', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Examenes.categorias')),
            ],
        ),
    ]
