# Generated by Django 5.1 on 2024-09-27 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Examenes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorias',
            options={'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='examenes',
            options={'verbose_name': 'Examen', 'verbose_name_plural': 'Examenes'},
        ),
    ]
