# Generated by Django 5.1 on 2024-10-10 22:49

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Examenes', '0002_alter_categorias_options_alter_examenes_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examenes',
            name='Descripción',
            field=django_quill.fields.QuillField(),
        ),
    ]
