# Generated by Django 5.1 on 2024-10-11 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Examenes', '0003_alter_examenes_descripción'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examenes',
            name='Descripción',
            field=models.TextField(verbose_name='Descripción'),
        ),
    ]
