# Generated by Django 5.1 on 2024-10-11 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Examenes', '0004_alter_examenes_descripción'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorias',
            old_name='ID_Categoría',
            new_name='ID_Categoria',
        ),
        migrations.RenameField(
            model_name='categorias',
            old_name='Nombre_Categoría',
            new_name='Nombre_Categoria',
        ),
        migrations.RenameField(
            model_name='examenes',
            old_name='Categoría',
            new_name='Categoria',
        ),
        migrations.RenameField(
            model_name='examenes',
            old_name='Descripción',
            new_name='Descripcion',
        ),
        migrations.RenameField(
            model_name='examenes',
            old_name='Duración_Límite',
            new_name='Duracion_Limite',
        ),
        migrations.RenameField(
            model_name='examenes',
            old_name='Fecha_Creación',
            new_name='Fecha_Creacion',
        ),
    ]
