# Generated by Django 5.1 on 2024-09-27 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='genero',
            field=models.CharField(choices=[('M', 'Hombre'), ('F', 'Mujer')], default='M', max_length=1, verbose_name='Genero'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuarios',
            name='identificacion',
            field=models.CharField(default='1', max_length=20, verbose_name='Documento de identidad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuarios',
            name='telefono',
            field=models.CharField(default='999-999-9999', max_length=15, verbose_name='Telefono'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='Rol',
            field=models.CharField(choices=[('A', 'Administrador'), ('O', 'Orientador'), ('D', 'Docente'), ('E', 'Estudinte')], max_length=1, verbose_name='Roles'),
        ),
    ]
