# Generated by Django 5.1 on 2024-10-18 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0004_remove_usuarios_contraseña_usuarios_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='Contraseña',
        ),
    ]
