# Generated by Django 5.1 on 2024-10-18 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0005_remove_usuarios_contraseña'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='Rol',
            field=models.CharField(blank=True, choices=[('A', 'Administrador'), ('O', 'Orientador'), ('D', 'Docente'), ('E', 'Estudinte')], max_length=1, verbose_name='Roles'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Hombre'), ('F', 'Mujer')], max_length=1, verbose_name='Genero'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, verbose_name='Telefono'),
        ),
    ]
