# Generated by Django 5.1 on 2024-09-27 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Respuestas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='respuestas',
            options={'verbose_name': 'Respuestas del Usuario', 'verbose_name_plural': 'Respuestas'},
        ),
    ]
